language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: Giqq1yd1o3OuXaETCk8S7gaXM5beK9THl+lHNJGjG5CjgYzVJLSsGKg2sli581uqKwY01zRAR2srVpu7HjIhjjTXUo/o1rdDoQ0lPkLbdzMpIGgAmS+maYjW83hlCWK19BbsXE4LVp5bzgO+5IXf/IvCp+11fqogIPRJPdfuBJI=
  on:
    tags: true
    all_branches: true
